# version: "3"
# services:
#   # defining a service called climber
#   climber:
#     # adding a name for the service
#     container_name: hlmitchell/climber
#     # restart container automatically if it fails
#     restart: always
#     # build the climber image using the Dockerfile in the current directory
#     build: .
#     # map the host port to the container port specified in Dockerfile
#     ports:
#       - "8080:8080"